# Generated by Django 4.2.1 on 2023-05-24 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userroom_creation_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userroom',
            name='id_room',
        ),
        migrations.RemoveField(
            model_name='userroom',
            name='id_user',
        ),
        migrations.AddField(
            model_name='userroom',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.room'),
        ),
        migrations.AddField(
            model_name='userroom',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user'),
        ),
    ]
