# Generated by Django 4.1.5 on 2023-05-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_userroom_id_room_remove_userroom_id_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(null=True)),
                ('users', models.ManyToManyField(null=True, to='api.user')),
            ],
        ),
    ]
