openapi: 3.0.3
info:
  title: Monopoly API
  version: 0.0.1

tags:
  - name: monopoly
    description: Monopoly API

servers:
  - url: http://127.0.0.1
    description: Local Monopoly API

paths:
  /test:
    get:
      tags:
        - monopoly
      summary: Test
      description: Test method
      operationId: testId
      responses:
        '200':
          description: Successful test operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Test'

components:
  schemas:
    Test:
      type: object
      properties:
        token:
          type: string
          example: example test
        test:
          type: string
          example: example test
