# Generated by Django 4.2.1 on 2023-05-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_players', models.IntegerField(default=4)),
                ('current_players', models.IntegerField()),
                ('starting_balance', models.IntegerField(default=0)),
                ('creation_datetime', models.DateTimeField()),
            ],
        ),
    ]
