# Generated by Django 4.2.1 on 2023-05-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_name_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_room', models.ManyToManyField(to='api.room')),
                ('id_user', models.ManyToManyField(to='api.user')),
            ],
        ),
    ]
