# Generated by Django 4.2.1 on 2023-05-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroom',
            name='creation_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
