# Generated by Django 4.1.5 on 2023-06-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_transaction_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='users',
            field=models.ManyToManyField(to='api.user'),
        ),
    ]
