version: "3.7"

services:  
  mysql:
    image: mysql:8.0.25
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=111
      - TZ=UTC
    volumes:
      - ${DATABASE_HOME}/mysql8:/var/lib/mysql

  python:
    restart: always
    build:
      context: .
      dockerfile: ./python/Dockerfile
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on:
      - mysql

  nginx:
    restart: always
    image: nginx:latest
    expose:
      - 8080
    ports:
      - "80:8080"
    volumes:
      - ../../frontend/src:/srv/www/monopoly
      - ./logs:/srv/www/monopoly/logs
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - python
